/*
*author: Jewel Rana
*this component is auto generated by Code Generator for Automation List
*since 12th August 2020
*/

import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

import { Constants } from '../../common';
import { Automationitem } from '../dto/automationitem';
import { ApiResponse } from '../../common/apiresponse';
import { HttpbaseService } from '../../common/httpbase.service';

const uri = Constants.apiUrl + '/automationitem/post';

@Injectable({
  providedIn: 'root'
})

export class AutomationitemService {
	constructor(
		private httpbase: HttpbaseService
	) {}
  
	getAutomationitemList(): Observable<ApiResponse> {
		return this.httpbase.getEntityList(uri);
	}

	getAutomationitemById(id): Observable<ApiResponse> {
		return this.httpbase.getEntityById(uri,id);		
	}
	
	getAutomationitemsByUniqueCode(code): Observable<ApiResponse> {
		return this.httpbase.getEntityByUniqueCode(uri,code);		
	}
	
	saveAutomationitem(automationitem: Automationitem): Observable<ApiResponse>{
		return this.httpbase.saveEntity(uri, automationitem);
	}

	deleteAutomationitem(automationitem: Automationitem): Observable<ApiResponse>{
		return this.httpbase.deleteEntity(uri, automationitem);	
	}	
}
