/*
 *author: Jewel Rana
 *this component is auto generated by Code Generator for Automation List
 *since 12th August 2020
 */

import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-automationitem",
  templateUrl: "./automationitem.component.html",
  styleUrls: ["./automationitem.component.css"],
})
export class AutomationitemComponent implements OnInit {
  constructor() {}

  ngOnInit() {}
}
