/*
 *author: Jewel Rana
 *this component is auto generated by Code Generator for Automation List
 *since 12th August 2020
 */

import { BaseEntity } from "../../common/baseentity";

export class Automationitem extends BaseEntity {
  automationId: string;
  automationName: string;
  automationCriteria: string;
  development: string;
  isActive: boolean;
  remarks: string;
  contacts: string;
  contactEmails: string;
}



export interface Address {
  // street: string;
  // postcode: string;
  name: string;
  email: string;
}
